openapi: 3.0.3
info:
  title: I_ServiceInformation
  description:  Über diese Schnittstelle werden Informationen über den KIM Fachdienst abgefragt
  version: 1.0.0
  ### 1.0.0
  # - initial Version of I_ServiceInformation

externalDocs:
  description: GitHub - Dokumentation
  url: https://github.com/gematik/api-kim
servers:
- url: /ServiceInformation/v1.0/
  # Die URL muss wie folgt gebildet werden:
  # https://<FQDN gemäß DNS-SD SRV RR>:<Port gemäß DNS-SD SRV RR><Base-path gemäß TXT RR><path gemäß yaml Datei>
tags:
- name: ServiceInformation

paths:
##--
##------
  /:
    get:
      tags:
      - ServiceInformation
      summary: Informationen über den KIM Fachdienst abfragen
      description: Informationen über den KIM Fachdienst abfragen
      operationId: getServiceInformation

      responses:
        200:
          description: OK
             # Rückgabe der Informationen über den KIM Fachdienst
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceInformation'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

##--
##------
components:

  schemas:

    ServiceInformation:
      type: object
      properties:
        passwordPolicyRegEx:
          type: string
          example:
            passwordPolicyRegEx: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[*.!@$%^&(){}[]:;<>,.?/~_+-=|\]).{8,64}$
          description: Gibt die Password Policy alsregulären Ausdruck an, die der AccountManager verlangt.
        passwordPolicyDisplay:
          type: string
          example:
            passwordPolicyDisplay: Mindestens eine Zahl [0-9]
                                  Mindestens ein Kleinbuchstabe [a-z]
                                  Mindestens ein Großbuchstabe [A-Z]
                                  Mindestens ein Sonderzeichen [*.!@#$%^&(){}[]:;<>,.?/~_+-=|\]
                                  Mindestlänge 8 Zeichen
                                  Maximallänge 64.
          description: Gibt die Password Policy in Textform an, die der AccountManager verlangt.


    Error:
      type: object
      properties:
        message:
          type: string
